const KEY="dividir-conta-v1";let state=JSON.parse(localStorage.getItem(KEY)||"null")||{name:"",currency:"BRL",people:[],expenses:[]};let splitMode="equal";
const $=id=>document.getElementById(id), money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:state.currency}).format(v||0);
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function init(){ $("eventName").value=state.name;$("currency").value=state.currency;$("expenseDate").value=new Date().toISOString().slice(0,10); render()}
function render(){renderPeople();renderPayer();renderSplit();renderExpenses();renderBalances();renderStats();renderSettlements()}
function renderPeople(){$("people").innerHTML=state.people.length?state.people.map((p,i)=>'<span class="chip">'+esc(p)+' <button title="Remover" onclick="removePerson('+i+')">×</button></span>').join(""):'<span class="muted">Adicione as pessoas que participarão.</span>'}
function renderPayer(){$("expensePayer").innerHTML=state.people.map(p=>'<option>'+esc(p)+'</option>').join("")}
function selectedPeople(){return [...document.querySelectorAll(".split-check:checked")].map(x=>x.value)}
function renderSplit(){if(splitMode==="equal"){$("splitEqual").innerHTML=state.people.length?state.people.map(p=>'<label style="display:flex;flex-direction:row;align-items:center;margin:7px 0;font-weight:500"><input class="split-check" type="checkbox" value="'+esc(p)+'" checked style="width:auto;margin-right:8px">'+esc(p)+'</label>').join(""):'<div class="empty">Adicione participantes primeiro.</div>';$("splitCustom").classList.add("hidden");$("splitEqual").classList.remove("hidden")}else{$("splitCustom").classList.remove("hidden");$("splitEqual").classList.add("hidden");$("splitCustom").innerHTML=state.people.length?state.people.map(p=>'<div class="custom-row"><div class="chip">'+esc(p)+'</div><input class="custom-value" data-person="'+esc(p)+'" type="number" min="0" step="0.01" placeholder="0,00"></div>').join(""):'<div class="empty">Adicione participantes primeiro.</div>'}}
function renderExpenses(){let el=$("expenses");if(!state.expenses.length){el.innerHTML='<div class="empty">Nenhuma despesa adicionada.</div>';return}el.innerHTML=state.expenses.map((e,i)=>'<div class="expense"><div><strong>'+esc(e.desc)+'</strong><br><small>'+esc(e.payer)+' pagou · '+e.date+' · dividido entre '+e.shares.length+' pessoa(s)</small></div><div><strong>'+money(e.amount)+'</strong><br><button class="small" style="background:#feecec;color:#a52222" onclick="removeExpense('+i+')">Excluir</button></div></div>').join("")}
function calculate(){let bal=Object.fromEntries(state.people.map(p=>[p,0]));state.expenses.forEach(e=>{bal[e.payer]=(bal[e.payer]||0)+e.amount;e.shares.forEach(s=>bal[s.person]-=s.amount)});return bal}
function renderBalances(){let b=calculate();$("balances").innerHTML=state.people.length?state.people.map(p=>'<div class="balance"><span>'+esc(p)+'</span><strong class="'+(b[p]>=0?'positive':'negative')+'">'+(b[p]>=0?'+':'')+money(b[p])+'</strong></div>').join(""):'<div class="empty">Adicione participantes.</div>'}
function renderSettlements(){let b=calculate(),cred=Object.entries(b).filter(([,v])=>v>.005).map(([p,v])=>({p,v})).sort((a,z)=>z.v-a.v),debt=Object.entries(b).filter(([,v])=>v<-.005).map(([p,v])=>({p,v:-v})).sort((a,z)=>z.v-a.v),out=[];let i=0,j=0;while(i<cred.length&&j<debt.length){let n=Math.min(cred[i].v,debt[j].v);out.push({from:debt[j].p,to:cred[i].p,value:n});cred[i].v-=n;debt[j].v-=n;if(cred[i].v<.005)i++;if(debt[j].v<.005)j++}$("settlements").innerHTML=out.length?out.map(x=>'<div class="settle"><span><strong>'+esc(x.from)+'</strong> paga <strong>'+esc(x.to)+'</strong></span><strong>'+money(x.value)+'</strong></div>').join(""):'<div class="empty">Tudo quitado. Ninguém precisa pagar ninguém.</div>'}
function renderStats(){$("total").textContent=money(state.expenses.reduce((a,e)=>a+e.amount,0));$("expenseCount").textContent=state.expenses.length;$("personCount").textContent=state.people.length}
function addPerson(){let n=$("personName").value.trim();if(!n)return;if(state.people.some(p=>p.toLowerCase()===n.toLowerCase()))return alert("Essa pessoa já foi adicionada.");state.people.push(n);$("personName").value="";save()}
function removePerson(i){let p=state.people[i];if(state.expenses.some(e=>e.payer===p||e.shares.some(s=>s.person===p)))return alert("Não é possível remover alguém que já participa de uma despesa.");state.people.splice(i,1);save()}
function addExpense(){let desc=$("expenseDesc").value.trim(),amount=Number($("expenseAmount").value),payer=$("expensePayer").value,date=$("expenseDate").value||new Date().toISOString().slice(0,10);if(!desc||!amount||amount<=0||!payer)return alert("Preencha descrição, valor e quem pagou.");let shares=[];if(splitMode==="equal"){let ps=selectedPeople();if(!ps.length)return alert("Selecione ao menos uma pessoa.");let cents=Math.round(amount*100),base=Math.floor(cents/ps.length),rest=cents%ps.length;shares=ps.map((p,i)=>({person:p,amount:(base+(i<rest?1:0))/100}))}else{shares=[...document.querySelectorAll(".custom-value")].map(x=>({person:x.dataset.person,amount:Number(x.value)||0})).filter(x=>x.amount>0);let sum=shares.reduce((a,x)=>a+x.amount,0);if(Math.abs(sum-amount)>.005)return alert("A soma das divisões deve ser igual ao valor da despesa.");if(!shares.length)return alert("Informe as partes da despesa.")}state.expenses.push({desc,amount,payer,date,shares});$("expenseDesc").value="";$("expenseAmount").value="";save()}
function removeExpense(i){state.expenses.splice(i,1);save()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
$("addPerson").onclick=addPerson;$("personName").onkeydown=e=>{if(e.key==="Enter")addPerson()};$("addExpense").onclick=addExpense;$("clearExpenses").onclick=()=>{if(confirm("Apagar todas as despesas deste evento?")){state.expenses=[];save()}};$("resetBtn").onclick=()=>{if(confirm("Criar um evento novo e apagar os dados atuais?")){state={name:"",currency:"BRL",people:[],expenses:[]};save();location.reload()}};$("eventName").oninput=e=>{state.name=e.target.value;localStorage.setItem(KEY,JSON.stringify(state))};$("currency").onchange=e=>{state.currency=e.target.value;save()};document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{splitMode=b.dataset.mode;document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("active",x===b));renderSplit()});init();
